Repository octokit/webhooks, pull requests merged in 2020-05, with the labels that each got.

#87 feat: `installation.{suspend,unsuspend}`
  cache/event-types-and-payloads.html
  index.json
  lib/workarounds.js
Labels: bug

#91 add basic tests for exported module
  package.json
  test.js
Labels: feature

#98 feat: event descriptions
  index.json
  lib/check-or-update-webhooks.js
  lib/section-to-webhook.js
  lib/workarounds.js
  package-lock.json
  package.json
  schema.js
  test.js
Labels: feature

#100 feat: new sponsorship events: `cancelled`, `edited`, `pending_cancellation`, `tier_changed`
  cache/event-types-and-payloads.html
  index.json
  lib/get-html.js
  lib/get-ping-webhook.js
  lib/get-sections.js
  lib/section-to-webhook.js
  lib/workarounds.js
Labels: feature

#101 style: replace standard with prettier
  .github/workflows/update-prettier.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  bin/octokit-webhooks.js
  index.json
  lib/cache.js
  lib/check-or-update-webhooks.js
  lib/create-pr-on-change.js
  lib/get-actions-and-examples-from-payloads.js
  lib/get-html.js
  lib/get-sections.js
  lib/section-to-webhook.js
  lib/workarounds.js
  package-lock.json
  package.json
  schema.js
  test.js
Labels: maintenance

#103 Replace Greenkeeper with Dependabot
  .github/dependabot.yml
  .github/workflows/test.yml
  .github/workflows/update-prettier.yml
  README.md
Labels: maintenance
