Repository octokit/webhooks, pull requests merged in 2020-09, with the labels that each got.

#168 refactor: remove obsolete remains of Travis CI
  README.md
  lib/check-or-update-webhooks.js
  lib/create-pr-on-change.js
  package-lock.json
Labels: maintenance

#175 build: only cache relevant HTML
  cache/webhook-events-and-payloads.html
  lib/get-html.js
Labels: maintenance

#177 fix: add installation object to pull_request_review and pull_request_review_comment events
  index.json
  payload-examples/api.github.com/pull_request_review.submitted.payload.json
  payload-examples/api.github.com/pull_request_review_comment.created.payload.json
Labels: bug

#178 docs(README): new documentation url for "GitHub’s Webhooks Event Types & Payloads" link
  README.md
Labels: bug, documentation
