Repository octokit/webhooks, pull requests merged in 2020-12, with the labels that each got.

#222 fix: add missing example for check_run.requested_action
  index.json
  payload-examples/api.github.com/check_run.requested_action.payload.json
Labels: maintenance

#225 feat: add payload for organisation webhook
  index.json
  lib/get-actions-and-examples-from-payloads.js
  payload-examples/api.github.com/README.md
  payload-examples/api.github.com/ping.with-organisation.payload.json
Labels: maintenance

#230 feat: add examples of payloads with organizations
  index.json
  payload-examples/api.github.com/repository.privatized-with-organization.payload.json
  payload-examples/api.github.com/repository.publicized-with-organization.payload.json
  payload-examples/api.github.com/repository_vulnerability_alert.create-with-gh-alert.payload.json
  payload-examples/api.github.com/repository_vulnerability_alert.create-with-organization.payload.json
Labels: maintenance

#233 feat: add example of `removed_from_repository` action for team event
  index.json
  payload-examples/api.github.com/team.removed_from_repository.payload.json
Labels: feature

#235 feat: add example of `repo.edit` action payload
  index.json
  payload-examples/api.github.com/repository.edited.payload.json
Labels: maintenance

#238 fix: event payload structure
  index.json
  payload-examples/api.github.com/project_card.deleted.payload.json
  payload-examples/api.github.com/project_card.deleted.with-installation.payload.json
  payload-examples/api.github.com/project_card.deleted.with-org.payload.json
  payload-examples/api.github.com/repository.transferred.payload.json
  payload-examples/api.github.com/repository.transferred.with-instalation.payload.json
  payload-examples/api.github.com/repository.transferred.with-organization.payload.json
Labels: bug

#239 chore: add prettier config
  package.json
Labels: maintenance

#241 fix(deps): move `prettier` to `devDependencies`
  package-lock.json
  package.json
Labels: maintenance
