Repository octokit/webhooks, pull requests merged in 2021-02, with the labels that each got.

#346 fix: add missing properties to `User` interface
  payload-schemas/schemas/common/repository.schema.json
  payload-schemas/schemas/common/user.schema.json
  schema.d.ts
Labels: bug

#345 fix: use `allOf` for `repository` property in `repository` event schemas
  payload-schemas/schemas/repository/archived.schema.json
  payload-schemas/schemas/repository/privatized.schema.json
  payload-schemas/schemas/repository/publicized.schema.json
  payload-schemas/schemas/repository/unarchived.schema.json
  schema.d.ts
Labels: bug

#348 feat: create `Issue` interface
  payload-schemas/schemas/common/issue.schema.json
  payload-schemas/schemas/issue_comment/created.schema.json
  payload-schemas/schemas/issue_comment/deleted.schema.json
  payload-schemas/schemas/issue_comment/edited.schema.json
  payload-schemas/schemas/issues/assigned.schema.json
  payload-schemas/schemas/issues/closed.schema.json
  payload-schemas/schemas/issues/deleted.schema.json
  payload-schemas/schemas/issues/demilestoned.schema.json
  payload-schemas/schemas/issues/edited.schema.json
  payload-schemas/schemas/issues/labeled.schema.json
  payload-schemas/schemas/issues/locked.schema.json
  payload-schemas/schemas/issues/milestoned.schema.json
  payload-schemas/schemas/issues/opened.schema.json
  payload-schemas/schemas/issues/pinned.schema.json
  payload-schemas/schemas/issues/reopened.schema.json
  payload-schemas/schemas/issues/transferred.schema.json
  payload-schemas/schemas/issues/unassigned.schema.json
  payload-schemas/schemas/issues/unlabeled.schema.json
  payload-schemas/schemas/issues/unlocked.schema.json
  payload-schemas/schemas/issues/unpinned.schema.json
  schema.d.ts
Labels: feature

#350 feat: create `Membership` interface
  payload-schemas/schemas/common/membership.schema.json
  payload-schemas/schemas/organization/deleted.schema.json
  payload-schemas/schemas/organization/member_added.schema.json
  payload-schemas/schemas/organization/member_removed.schema.json
  payload-schemas/schemas/organization/renamed.schema.json
  schema.d.ts
Labels: feature

#349 feat: create `MarketplacePurchase` interface
  payload-schemas/schemas/common/marketplace-purchase.schema.json
  payload-schemas/schemas/marketplace_purchase/cancelled.schema.json
  payload-schemas/schemas/marketplace_purchase/changed.schema.json
  payload-schemas/schemas/marketplace_purchase/pending_change.schema.json
  payload-schemas/schemas/marketplace_purchase/pending_change_cancelled.schema.json
  payload-schemas/schemas/marketplace_purchase/purchased.schema.json
  schema.d.ts
Labels: feature

#351 feat: create `Workflow` interface
  payload-schemas/schemas/common/workflow.schema.json
  payload-schemas/schemas/workflow_run/completed.schema.json
  payload-schemas/schemas/workflow_run/requested.schema.json
  schema.d.ts
Labels: feature

#352 feat: create `WorkflowRun` interface
  payload-schemas/schemas/common/workflow-run.schema.json
  payload-schemas/schemas/workflow_run/completed.schema.json
  payload-schemas/schemas/workflow_run/requested.schema.json
  schema.d.ts
Labels: feature

#355 fix: adjust `check_run#completed` schema
  index.json
  payload-examples/api.github.com/check_run/completed.1.payload.json
  payload-schemas/schemas/check_run/completed.schema.json
  schema.d.ts
Labels: bug

#356 fix: mark `author` and `committer` as nullable in `status` schema
  index.json
  payload-examples/api.github.com/status/with-author-committer-null.payload.json
  payload-schemas/schemas/status/event.schema.json
  schema.d.ts
Labels: bug

#344 chore: add `prettier-plugin-packagejson`
  package-lock.json
  package.json
Labels: maintenance

#360 fix: use common `Repository` interface for `PublicEvent#repository`
  payload-schemas/schemas/public/event.schema.json
  schema.d.ts
Labels: bug

#357 feat: create `Project` interface
  payload-schemas/schemas/common/project.schema.json
  payload-schemas/schemas/project/closed.schema.json
  payload-schemas/schemas/project/created.schema.json
  payload-schemas/schemas/project/deleted.schema.json
  payload-schemas/schemas/project/edited.schema.json
  payload-schemas/schemas/project/reopened.schema.json
  schema.d.ts
Labels: feature

#358 feat: create `ProjectCard` interface
  payload-schemas/schemas/common/project-card.schema.json
  payload-schemas/schemas/project_card/converted.schema.json
  payload-schemas/schemas/project_card/created.schema.json
  payload-schemas/schemas/project_card/deleted.schema.json
  payload-schemas/schemas/project_card/edited.schema.json
  payload-schemas/schemas/project_card/moved.schema.json
  schema.d.ts
Labels: feature

#359 feat: create `ProjectColumn` interface
  payload-schemas/schemas/common/project-column.schema.json
  payload-schemas/schemas/project_column/created.schema.json
  payload-schemas/schemas/project_column/deleted.schema.json
  payload-schemas/schemas/project_column/edited.schema.json
  payload-schemas/schemas/project_column/moved.schema.json
  schema.d.ts
Labels: feature

#361 fix: add enum to delete#ref_type to match the create event
  payload-schemas/schemas/delete/event.schema.json
  schema.d.ts
Labels: bug

#363 fix: change the replacement pattern to rewrite URLs as absolute again
  index.json
  lib/section-to-webhook.ts
Labels: bug

#353 feat: add properties to index.json
  index.json
  lib/check-or-update-webhooks.ts
  lib/section-to-webhook.ts
  lib/types.ts
Labels: feature

#364 fix: add missing properties
  index.json
  lib/section-to-webhook.ts
Labels: bug

#366 Update Codescanning Alert Payload Schemas to Include a Sender Field
  index.json
  payload-examples/api.github.com/code_scanning_alert/reopened.payload.json
  payload-examples/api.github.com/code_scanning_alert/reopened.with-organization.payload.json
  payload-schemas/schemas/code_scanning_alert/appeared_in_branch.schema.json
  payload-schemas/schemas/code_scanning_alert/created.schema.json
  payload-schemas/schemas/code_scanning_alert/fixed.schema.json
  payload-schemas/schemas/code_scanning_alert/reopened.schema.json
  schema.d.ts
Labels: feature

#369 feat: use the Github org values for CodeScanningAlert
  index.json
  payload-examples/api.github.com/code_scanning_alert/reopened.payload.json
  payload-examples/api.github.com/code_scanning_alert/reopened.with-organization.payload.json
  payload-schemas/schemas/code_scanning_alert/appeared_in_branch.schema.json
  payload-schemas/schemas/code_scanning_alert/created.schema.json
  payload-schemas/schemas/code_scanning_alert/fixed.schema.json
  payload-schemas/schemas/code_scanning_alert/reopened.schema.json
  payload-schemas/schemas/common/github-org.schema.json
  schema.d.ts
Labels: feature

#375 refactor: use allOf for forkee property, like #345
  bin/utils/normalizeSchema.ts
  payload-schemas/schemas/fork/event.schema.json
  schema.d.ts
Labels: maintenance

#376 fix: use common `PullRequest` interface for `pull_request` events
  payload-schemas/schemas/pull_request/closed.schema.json
  payload-schemas/schemas/pull_request/converted_to_draft.schema.json
  payload-schemas/schemas/pull_request/opened.schema.json
  payload-schemas/schemas/pull_request/ready_for_review.schema.json
  payload-schemas/schemas/pull_request/reopened.schema.json
  schema.d.ts
Labels: bug

#377 refactor: create AlertInstance schema for CodeScaningAlertEvent#alert#instances
  payload-schemas/schemas/code_scanning_alert/appeared_in_branch.schema.json
  payload-schemas/schemas/code_scanning_alert/closed_by_user.schema.json
  payload-schemas/schemas/code_scanning_alert/created.schema.json
  payload-schemas/schemas/code_scanning_alert/fixed.schema.json
  payload-schemas/schemas/code_scanning_alert/reopened.schema.json
  payload-schemas/schemas/code_scanning_alert/reopened_by_user.schema.json
  payload-schemas/schemas/common/alert-instance.schema.json
  schema.d.ts
Labels: maintenance

#379 fix: adjust GitHubOrg schema
  index.json
  payload-examples/api.github.com/code_scanning_alert/reopened.payload.json
  payload-examples/api.github.com/code_scanning_alert/reopened.with-organization.payload.json
  payload-schemas/schemas/common/github-org.schema.json
  schema.d.ts
Labels: bug

#383 fix: cleanup properties in issues and pull_request schemas
  payload-schemas/schemas/issues/assigned.schema.json
  payload-schemas/schemas/issues/closed.schema.json
  payload-schemas/schemas/issues/deleted.schema.json
  payload-schemas/schemas/issues/demilestoned.schema.json
  payload-schemas/schemas/issues/edited.schema.json
  payload-schemas/schemas/issues/labeled.schema.json
  payload-schemas/schemas/issues/locked.schema.json
  payload-schemas/schemas/issues/milestoned.schema.json
  payload-schemas/schemas/issues/opened.schema.json
  payload-schemas/schemas/issues/pinned.schema.json
  payload-schemas/schemas/issues/reopened.schema.json
  payload-schemas/schemas/issues/transferred.schema.json
  payload-schemas/schemas/issues/unassigned.schema.json
  payload-schemas/schemas/issues/unlabeled.schema.json
  payload-schemas/schemas/issues/unlocked.schema.json
  payload-schemas/schemas/issues/unpinned.schema.json
  payload-schemas/schemas/pull_request/assigned.schema.json
  payload-schemas/schemas/pull_request/closed.schema.json
  payload-schemas/schemas/pull_request/converted_to_draft.schema.json
  payload-schemas/schemas/pull_request/edited.schema.json
  payload-schemas/schemas/pull_request/labeled.schema.json
  payload-schemas/schemas/pull_request/locked.schema.json
  payload-schemas/schemas/pull_request/opened.schema.json
  payload-schemas/schemas/pull_request/ready_for_review.schema.json
  payload-schemas/schemas/pull_request/reopened.schema.json
  payload-schemas/schemas/pull_request/synchronize.schema.json
  payload-schemas/schemas/pull_request/unassigned.schema.json
  payload-schemas/schemas/pull_request/unlabeled.schema.json
  payload-schemas/schemas/pull_request/unlocked.schema.json
  schema.d.ts
Labels: bug

#384 refactor: use a common schema for CheckRunEvent#check_run.pull_request
  payload-schemas/schemas/check_run/completed.schema.json
  payload-schemas/schemas/check_run/created.schema.json
  payload-schemas/schemas/check_run/requested_action.schema.json
  payload-schemas/schemas/check_run/rerequested.schema.json
  payload-schemas/schemas/check_suite/completed.schema.json
  payload-schemas/schemas/check_suite/requested.schema.json
  payload-schemas/schemas/check_suite/rerequested.schema.json
  payload-schemas/schemas/common/check-run-pull-request.schema.json
  schema.d.ts
Labels: maintenance

#371 chore(payloads): add code scanning examples
  index.json
  payload-examples/api.github.com/code_scanning_alert/closed-by-user.payload.json
  payload-examples/api.github.com/code_scanning_alert/created.payload.json
  payload-examples/api.github.com/code_scanning_alert/fixed.payload.json
  payload-schemas/schemas/code_scanning_alert/closed_by_user.schema.json
  payload-schemas/schemas/code_scanning_alert/created.schema.json
  payload-schemas/schemas/code_scanning_alert/fixed.schema.json
  payload-schemas/schemas/code_scanning_alert/reopened.schema.json
  payload-schemas/schemas/common/alert-instance.schema.json
  payload-schemas/schemas/common/user.schema.json
  schema.d.ts
Labels: maintenance

#389 ci: fix PR mesage for webhooks cache update
  .github/workflows/update.yml
Labels: maintenance
