Repository octokit/webhooks, pull requests merged in 2021-04, with the labels that each got.

#430 fix: don't include `$id` property in compiled schema
  README.md
  bin/octokit-schema.ts
  bin/validate-schema.ts
  package.json
Labels: bug

#428 fix: type of `requester` property on `InstallationEvent` & `InstallationRepositoriesEvent` should be `User` and not `null`
  index.json
  payload-examples/api.github.com/installation/created.with-requester.payload.json
  payload-schemas/schemas/installation/created.schema.json
  payload-schemas/schemas/installation_repositories/added.schema.json
  schema.d.ts
Labels: bug

#411 Split components into seperate packages
  .github/workflows/release.yml
  CONTRIBUTING.md
  README.md
  bin/docs/octokit-schema.md
  bin/docs/octokit-types.md
  bin/octokit-schema.ts
  bin/octokit-types.ts
  bin/validate-payload-examples.ts
  bin/validate-schema.ts
  lib/check-or-update-webhooks.ts
  package-lock.json
  package.json
  payload-examples/README.md
  payload-examples/index.d.ts
  payload-examples/index.json
  payload-examples/package.json
  payload-schemas/README.md
  payload-schemas/package.json
  payload-types/README.md
  payload-types/package.json
  payload-types/schema.d.ts
  test.ts
Labels: maintenance

#433 ci(release): `package.json` configuration key is `"release"`, not `"releases"`
  package.json
Labels: maintenance

#437 fix: `username` property on `Committer` can be not present
  index.json
  payload-examples/api.github.com/push/with-no-username-committer.payload.json
  payload-schemas/schemas/common/commit.schema.json
  schema.d.ts
Labels: bug

#441 fix(schema): correct spelling error in `$id` property for `DiscussionTransferredEvent`
  payload-schemas/schemas/discussion/transferred.schema.json
Labels: bug

#442 lint: run formatter script
  payload-examples/api.github.com/code_scanning_alert/closed-by-user.payload.json
  payload-examples/api.github.com/code_scanning_alert/created.payload.json
  payload-examples/api.github.com/code_scanning_alert/fixed.payload.json
  payload-examples/api.github.com/project_card/moved.payload.json
  payload-schemas/schemas/common/alert-instance.schema.json
  payload-schemas/schemas/workflow_run/completed.schema.json
  payload-schemas/schemas/workflow_run/requested.schema.json
Labels: maintenance

#436 feat: split components into seperate packages
  .github/workflows/release.yml
  CONTRIBUTING.md
  README.md
  bin/docs/octokit-schema.md
  bin/docs/octokit-types.md
  bin/octokit-schema.ts
  bin/octokit-types.ts
  bin/validate-payload-examples.ts
  bin/validate-schema.ts
  lib/check-or-update-webhooks.ts
  package.json
  payload-examples/README.md
  payload-examples/index.d.ts
  payload-examples/index.json
  payload-examples/package.json
  payload-schemas/README.md
  payload-schemas/package.json
  payload-types/README.md
  payload-types/package.json
  payload-types/schema.d.ts
  test.ts
Labels: feature

#448 ci: fix release notification
  .github/workflows/release-notification.yml
Labels: maintenance

#439 feat: add new & missing properties to events
  payload-examples/api.github.com/deployment/payload.json
  payload-examples/api.github.com/deployment/with-installation.payload.json
  payload-examples/api.github.com/deployment_status/payload.json
  payload-examples/api.github.com/deployment_status/with-installation.payload.json
  payload-examples/api.github.com/security_advisory/published.payload.json
  payload-examples/api.github.com/security_advisory/updated.payload.json
  payload-examples/api.github.com/workflow_run/completed.payload.json
  payload-examples/api.github.com/workflow_run/requested.payload.json
  payload-examples/index.json
  payload-schemas/schemas/check_run/completed.schema.json
  payload-schemas/schemas/check_run/created.schema.json
  payload-schemas/schemas/check_run/requested_action.schema.json
  payload-schemas/schemas/check_run/rerequested.schema.json
  payload-schemas/schemas/code_scanning_alert/appeared_in_branch.schema.json
  payload-schemas/schemas/code_scanning_alert/closed_by_user.schema.json
  payload-schemas/schemas/code_scanning_alert/created.schema.json
  payload-schemas/schemas/code_scanning_alert/reopened.schema.json
  payload-schemas/schemas/code_scanning_alert/reopened_by_user.schema.json
  payload-schemas/schemas/common/committer.schema.json
  payload-schemas/schemas/common/installation.schema.json
  payload-schemas/schemas/common/repository.schema.json
  payload-schemas/schemas/common/workflow-run.schema.json
  payload-schemas/schemas/deployment/created.schema.json
  payload-schemas/schemas/deployment_status/created.schema.json
  payload-schemas/schemas/pull_request_review_comment/created.schema.json
  payload-schemas/schemas/pull_request_review_comment/deleted.schema.json
  payload-schemas/schemas/pull_request_review_comment/edited.schema.json
  payload-schemas/schemas/security_advisory/performed.schema.json
  payload-schemas/schemas/security_advisory/published.schema.json
  payload-schemas/schemas/security_advisory/updated.schema.json
  payload-schemas/schemas/status/event.schema.json
  payload-types/schema.d.ts
Labels: maintenance

#452 fix: replace all links with fully-qualified URLs
  lib/section-to-webhook.ts
  payload-examples/index.json
Labels: maintenance

#454 fix: update the webhook payloads with updated property information
  payload-examples/api.github.com/pull_request_review/dismissed.payload.json
  payload-examples/api.github.com/pull_request_review/submitted.payload.json
  payload-examples/api.github.com/pull_request_review/submitted.with-organization.payload.json
  payload-examples/api.github.com/pull_request_review_comment/created.payload.json
  payload-examples/api.github.com/pull_request_review_comment/created.with-organization.payload.json
  payload-examples/api.github.com/pull_request_review_comment/deleted.payload.json
  payload-examples/api.github.com/pull_request_review_comment/edited.payload.json
  payload-examples/api.github.com/workflow_run/completed.payload.json
  payload-examples/api.github.com/workflow_run/requested.payload.json
  payload-examples/index.json
  payload-schemas/schemas/check_run/created.schema.json
  payload-schemas/schemas/common/simple-pull-request.schema.json
  payload-schemas/schemas/common/workflow-run.schema.json
  payload-schemas/schemas/pull_request_review/edited.schema.json
  payload-schemas/schemas/pull_request_review_comment/created.schema.json
  payload-schemas/schemas/pull_request_review_comment/deleted.schema.json
  payload-schemas/schemas/pull_request_review_comment/edited.schema.json
  payload-schemas/schemas/security_advisory/performed.schema.json
  payload-schemas/schemas/security_advisory/published.schema.json
  payload-schemas/schemas/security_advisory/updated.schema.json
  payload-types/schema.d.ts
Labels: maintenance

#458 fix: update properties in `PullRequestReviewCommentEvent` and `WorkflowRunDispatchEvent`, plus some refactoring
  payload-examples/api.github.com/issue_comment/created.payload.json
  payload-examples/api.github.com/issue_comment/created.with-installation.payload.json
  payload-examples/api.github.com/issue_comment/created.with-organization.payload.json
  payload-examples/api.github.com/issue_comment/deleted.payload.json
  payload-examples/api.github.com/issue_comment/deleted.with-organization.payload.json
  payload-examples/api.github.com/pull_request_review_comment/created.payload.json
  payload-examples/api.github.com/pull_request_review_comment/created.with-organization.payload.json
  payload-examples/api.github.com/pull_request_review_comment/deleted.payload.json
  payload-examples/api.github.com/pull_request_review_comment/edited.payload.json
  payload-examples/index.json
  payload-schemas/schemas/common/issue-comment.schema.json
  payload-schemas/schemas/common/pull-request-review-comment.schema.json
  payload-schemas/schemas/issue_comment/created.schema.json
  payload-schemas/schemas/issue_comment/deleted.schema.json
  payload-schemas/schemas/issue_comment/edited.schema.json
  payload-schemas/schemas/pull_request_review_comment/created.schema.json
  payload-schemas/schemas/pull_request_review_comment/deleted.schema.json
  payload-schemas/schemas/pull_request_review_comment/edited.schema.json
  payload-schemas/schemas/workflow_dispatch/event.schema.json
  payload-types/schema.d.ts
Labels: maintenance

#459 feat: add new `changes` property to `ProjectColumnEditedEvent` and make `ProjectCard#content_url` optional
  payload-examples/api.github.com/project_column/edited.payload.json
  payload-examples/index.json
  payload-schemas/schemas/common/project-card.schema.json
  payload-schemas/schemas/project_column/edited.schema.json
  payload-types/schema.d.ts
Labels: maintenance

#463 ci(release): remove un-needed steps
  .github/workflows/release.yml
Labels: maintenance

#464 chore: cleanup un-needed entries in the root `package.json` and mark it as private
  package.json
Labels: maintenance

#465 chore: update paths give to prettier
  package.json
  tsconfig.json
Labels: maintenance

#462 fix: update `d.ts` for `payload-examples` to match the JSON
  .github/workflows/test.yml
  package-lock.json
  package.json
  payload-examples/index.d.ts
  payload-examples/package-lock.json
  payload-examples/package.json
Labels: bug, typescript

#466 fix: update `d.ts` for `payload-examples` to match the JSON
  .github/workflows/test.yml
  package-lock.json
  package.json
  payload-examples/index.d.ts
  payload-examples/package-lock.json
  payload-examples/package.json
Labels: bug, typescript

#468 fix(types): mark `WebhookDefinition#examples` to be an `Array`
  payload-examples/index.d.ts
Labels: bug, typescript

#469 feat: add missing permissions in `Installation#removed`, add `null` to various properties, list all events instead of `string[]`, add new example payloads for `Installation{Suspend,Unsuspend}Event`
  payload-examples/api.github.com/installation/suspend.payload.json
  payload-examples/api.github.com/installation/unsuspend.payload.json
  payload-examples/index.json
  payload-schemas/schemas/check_suite/completed.schema.json
  payload-schemas/schemas/check_suite/requested.schema.json
  payload-schemas/schemas/check_suite/rerequested.schema.json
  payload-schemas/schemas/common/installation.schema.json
  payload-schemas/schemas/installation/suspend.schema.json
  payload-schemas/schemas/installation/unsuspend.schema.json
  payload-schemas/schemas/push/event.schema.json
  payload-types/schema.d.ts
Labels: feature
