Repository octokit/webhooks, pull requests merged in 2021-05, with the labels that each got.

#471 fix(readme): Definition links in README's where 404ing
  README.md
  payload-types/README.md
Labels: bug, documentation

#474 feat: requester in `InstallationRepositoriesAddedEvent` can be `null` and is now set as required, `closed_at` in `IssueCommentEvent` isn't always `null`
  payload-examples/api.github.com/installation_repositories/added.payload.json
  payload-examples/index.json
  payload-schemas/schemas/installation_repositories/added.schema.json
  payload-schemas/schemas/issue_comment/created.schema.json
  payload-schemas/schemas/issue_comment/deleted.schema.json
  payload-types/schema.d.ts
Labels: maintenance

#475 feat: new `withdrawn` action for `security_advisory` event
  payload-examples/api.github.com/security_advisory/withdrawn.payload.json
  payload-examples/index.json
  payload-schemas/schemas/security_advisory/withdrawn.schema.json
  payload-types/schema.d.ts
Labels: maintenance

#478 fix: an issue's body can be empty and thus `null`
  payload-examples/api.github.com/issues/opened.with-empty-body.payload.json
  payload-examples/index.json
  payload-schemas/schemas/common/issue.schema.json
  payload-types/schema.d.ts
Labels: bug

#479 chore: pin prettier version and fix "Update Prettier" workflow
  .github/workflows/update-prettier.yml
  bin/octokit-schema.ts
  bin/utils/argv.ts
  lib/section-to-webhook.ts
  package-lock.json
  package.json
  payload-schemas/index.ts
Labels: maintenance

#490 Multiple fixes to webhooks schemas
  payload-examples/api.github.com/issues/demilestoned.payload.json
  payload-examples/api.github.com/issues/demilestoned.with-organization.payload.json
  payload-examples/api.github.com/issues/milestoned.payload.json
  payload-examples/api.github.com/issues/milestoned.with-organization.payload.json
  payload-examples/api.github.com/organization/member_invited.payload.json
  payload-examples/index.json
  payload-schemas/schemas/common/app.schema.json
  payload-schemas/schemas/common/issue.schema.json
  payload-schemas/schemas/common/team.schema.json
  payload-schemas/schemas/common/webhook-events.schema.json
  payload-schemas/schemas/issues/assigned.schema.json
  payload-schemas/schemas/issues/deleted.schema.json
  payload-schemas/schemas/issues/demilestoned.schema.json
  payload-schemas/schemas/issues/milestoned.schema.json
  payload-schemas/schemas/organization/member_invited.schema.json
  payload-schemas/schemas/project_card/moved.schema.json
  payload-schemas/schemas/pull_request/converted_to_draft.schema.json
  payload-schemas/schemas/pull_request/ready_for_review.schema.json
  payload-schemas/schemas/pull_request/review_request_removed.schema.json
  payload-schemas/schemas/pull_request/review_requested.schema.json
  payload-types/schema.d.ts
Labels: bug
