Repository octokit/webhooks, pull requests merged in 2021-01, with the labels that each got.

#242 feat: Add payload examples for 'pull_request.converted_to_draft' and 'pull_request.ready_for_review'
  index.json
  payload-examples/api.github.com/pull_request.converted_to_draft.payload.json
  payload-examples/api.github.com/pull_request.converted_to_draft.with-installation.payload.json
  payload-examples/api.github.com/pull_request.converted_to_draft.with-organization.payload.json
  payload-examples/api.github.com/pull_request.ready_for_review.payload.json
  payload-examples/api.github.com/pull_request.ready_for_review.with-installation.payload.json
  payload-examples/api.github.com/pull_request.ready_for_review.with-organization.payload.json
Labels: maintenance

#243 chore: Rename files, so that they are consistent
  index.json
  payload-examples/api.github.com/code_scanning_alert.reopened.payload.json
  payload-examples/api.github.com/code_scanning_alert.reopened.with-organization.payloa.json
  payload-examples/api.github.com/commit_comment.created.with-installation.payload.json
  payload-examples/api.github.com/create.with-installation.payload.json
  payload-examples/api.github.com/delete.with-installation.payload.json
  payload-examples/api.github.com/deployment.with-installation.payload.json
  payload-examples/api.github.com/deployment_status.with-installation.payloa.json
  payload-examples/api.github.com/fork.with-installation.payload.json
  payload-examples/api.github.com/gollum.with-installation.payload.json
  payload-examples/api.github.com/issue_comment.created.with-installation.payload.json
  payload-examples/api.github.com/issues.assigned.with-installation.payload.json
  payload-examples/api.github.com/label.created.with-installation.payload.json
  payload-examples/api.github.com/member.added.with-installation.payload.json
  payload-examples/api.github.com/membership.removed.with-installation.payload.json
  payload-examples/api.github.com/milestone.closed.with-installation.payload.json
  payload-examples/api.github.com/org_block.blocked.with-installation.payload.json
  payload-examples/api.github.com/organization.member_added.with-installationpayload.json
  payload-examples/api.github.com/page_build.with-installation.payload.json
  payload-examples/api.github.com/ping.with-organization.payload.json
  payload-examples/api.github.com/project_card.created.with-installation.payload.json
  payload-examples/api.github.com/project_card.deleted.with-organization.payload.json
  payload-examples/api.github.com/public.with-installation.payload.json
  payload-examples/api.github.com/push.with-installation.payload.json
  payload-examples/api.github.com/release.created.with-installation.payload.json
  payload-examples/api.github.com/repository.privatized.with-organization.payload.json
  payload-examples/api.github.com/repository.publicized.with-organization.payload.json
  payload-examples/api.github.com/repository.transferred.with-installation.payload.json
  payload-examples/api.github.com/repository_vulnerability_alert.create.with-gh-alert.payload.json
  payload-examples/api.github.com/repository_vulnerability_alert.create.with-organization.payload.json
  payload-examples/api.github.com/status.with-installation.payload.json
  payload-examples/api.github.com/team_add.with-installation.payload.json
  payload-examples/api.github.com/watch.started.with-installation.payload.json
Labels: maintenance

#245 fix: use `oneOf` for nullable types
  payload-schemas/schemas/check_run.schema.json
  payload-schemas/schemas/check_suite.schema.json
  payload-schemas/schemas/code_scanning_alert.schema.json
  payload-schemas/schemas/commit_comment.schema.json
  payload-schemas/schemas/common/installation.schema.json
  payload-schemas/schemas/common/organization.schema.json
  payload-schemas/schemas/content_reference.schema.json
  payload-schemas/schemas/create.schema.json
  payload-schemas/schemas/delete.schema.json
  payload-schemas/schemas/deploy_key.schema.json
  payload-schemas/schemas/deployment.schema.json
  payload-schemas/schemas/deployment_status.schema.json
  payload-schemas/schemas/fork.schema.json
  payload-schemas/schemas/gollum.schema.json
  payload-schemas/schemas/issue_comment.schema.json
  payload-schemas/schemas/issues.schema.json
  payload-schemas/schemas/label.schema.json
  payload-schemas/schemas/member.schema.json
  payload-schemas/schemas/membership.schema.json
  payload-schemas/schemas/milestone.schema.json
  payload-schemas/schemas/org_block.schema.json
  payload-schemas/schemas/organization.schema.json
  payload-schemas/schemas/package.schema.json
  payload-schemas/schemas/page_build.schema.json
  payload-schemas/schemas/ping.schema.json
  payload-schemas/schemas/project.schema.json
  payload-schemas/schemas/project_card.schema.json
  payload-schemas/schemas/project_column.schema.json
  payload-schemas/schemas/public.schema.json
  payload-schemas/schemas/pull_request.schema.json
  payload-schemas/schemas/pull_request_review.schema.json
  payload-schemas/schemas/pull_request_review_comment.schema.json
  payload-schemas/schemas/push.schema.json
  payload-schemas/schemas/release.schema.json
  payload-schemas/schemas/repository.schema.json
  payload-schemas/schemas/repository_dispatch.schema.json
  payload-schemas/schemas/repository_import.schema.json
  payload-schemas/schemas/repository_vulnerability_alert.schema.json
  payload-schemas/schemas/star.schema.json
  payload-schemas/schemas/status.schema.json
  payload-schemas/schemas/team.schema.json
  payload-schemas/schemas/team_add.schema.json
  payload-schemas/schemas/watch.schema.json
  payload-schemas/schemas/workflow_dispatch.schema.json
Labels: bug

#244 fix: common organization properties
  index.json
  payload-examples/api.github.com/check_run.completed.with-organization.payload.json
  payload-examples/api.github.com/check_run.created.with-organization.payload.json
  payload-examples/api.github.com/check_run.rerequested.with-organization.payload.json
  payload-examples/api.github.com/check_suite.completed.with-organization.payload.json
  payload-examples/api.github.com/check_suite.requested.with-organization.payload.json
  payload-examples/api.github.com/check_suite.rerequested.with-organization.payload.json
  payload-examples/api.github.com/commit_comment.created.with-installation.payload.json
  payload-examples/api.github.com/commit_comment.created.with-organization.payload.json
  payload-examples/api.github.com/create.with-organization.payload.json
  payload-examples/api.github.com/delete.with-organization.payload.json
  payload-examples/api.github.com/issue_comment.created.with-installation.payload.json
  payload-examples/api.github.com/issue_comment.created.with-organization.payload.json
  payload-examples/api.github.com/issue_comment.deleted.with-organization.payload.json
  payload-examples/api.github.com/issue_comment.edited.with-organization.payload.json
  payload-examples/api.github.com/issues.assigned.with-organization.payload.json
  payload-examples/api.github.com/issues.demilestoned.with-organization.payload.json
  payload-examples/api.github.com/issues.edited.with-organization.payload.json
  payload-examples/api.github.com/issues.labeled.with-organization.payload.json
  payload-examples/api.github.com/issues.locked.with-organization.payload.json
  payload-examples/api.github.com/issues.milestoned.with-organization.payload.json
  payload-examples/api.github.com/issues.opened.with-organization.payload.json
  payload-examples/api.github.com/issues.unassigned.with-organization.payload.json
  payload-examples/api.github.com/issues.unlabeled.with-organization.payload.json
  payload-examples/api.github.com/issues.unlocked.with-organization.payload.json
  payload-examples/api.github.com/project_card.created.with-organization.payload.json
  payload-examples/api.github.com/project_card.deleted.with-organization.payload.json
  payload-examples/api.github.com/pull_request.assigned.with-organization.payload.json
  payload-examples/api.github.com/pull_request.closed.with-organization.payload.json
  payload-examples/api.github.com/pull_request.labeled.with-organization.payload.json
  payload-examples/api.github.com/pull_request.locked.with-organization.payload.json
  payload-examples/api.github.com/pull_request.opened.with-organization.payload.json
  payload-examples/api.github.com/pull_request.reopened.with-organization.payload.json
  payload-examples/api.github.com/pull_request.unassigned.with-organization.payload.json
  payload-examples/api.github.com/pull_request.unlabeled.with-organization.payload.json
  payload-examples/api.github.com/pull_request.unlocked.with-organization.payload.json
  payload-examples/api.github.com/pull_request_review.submitted.with-organization.payload.json
  payload-examples/api.github.com/pull_request_review_comment.created.with-organization.payload.json
  payload-examples/api.github.com/push.with-organization.payload.json
  payload-schemas/schemas/common/organization.schema.json
Labels: bug

#246 feat: Be more explicit on the changes property of the repository schema
  payload-schemas/schemas/repository.schema.json
Labels: feature

#247 feat: Add installation.new_permissions_accepted payload and schema
  index.json
  payload-examples/api.github.com/installation.new_permissions_accepted.payload.json
  payload-schemas/schemas/installation.schema.json
Labels: feature

#251 fix: installation and organization properties are never null
  payload-schemas/schemas/check_run.schema.json
  payload-schemas/schemas/check_suite.schema.json
  payload-schemas/schemas/code_scanning_alert.schema.json
  payload-schemas/schemas/commit_comment.schema.json
  payload-schemas/schemas/content_reference.schema.json
  payload-schemas/schemas/create.schema.json
  payload-schemas/schemas/delete.schema.json
  payload-schemas/schemas/deploy_key.schema.json
  payload-schemas/schemas/deployment.schema.json
  payload-schemas/schemas/deployment_status.schema.json
  payload-schemas/schemas/fork.schema.json
  payload-schemas/schemas/gollum.schema.json
  payload-schemas/schemas/issue_comment.schema.json
  payload-schemas/schemas/issues.schema.json
  payload-schemas/schemas/label.schema.json
  payload-schemas/schemas/member.schema.json
  payload-schemas/schemas/membership.schema.json
  payload-schemas/schemas/milestone.schema.json
  payload-schemas/schemas/org_block.schema.json
  payload-schemas/schemas/organization.schema.json
  payload-schemas/schemas/package.schema.json
  payload-schemas/schemas/page_build.schema.json
  payload-schemas/schemas/ping.schema.json
  payload-schemas/schemas/project.schema.json
  payload-schemas/schemas/project_card.schema.json
  payload-schemas/schemas/project_column.schema.json
  payload-schemas/schemas/public.schema.json
  payload-schemas/schemas/pull_request.schema.json
  payload-schemas/schemas/pull_request_review.schema.json
  payload-schemas/schemas/pull_request_review_comment.schema.json
  payload-schemas/schemas/push.schema.json
  payload-schemas/schemas/release.schema.json
  payload-schemas/schemas/repository.schema.json
  payload-schemas/schemas/repository_dispatch.schema.json
  payload-schemas/schemas/repository_import.schema.json
  payload-schemas/schemas/repository_vulnerability_alert.schema.json
  payload-schemas/schemas/star.schema.json
  payload-schemas/schemas/status.schema.json
  payload-schemas/schemas/team.schema.json
  payload-schemas/schemas/team_add.schema.json
  payload-schemas/schemas/watch.schema.json
  payload-schemas/schemas/workflow_dispatch.schema.json
Labels: bug

#249 chore: Fix typos in payload examples file names
  payload-examples/api.github.com/code_scanning_alert.reopened.with-organization.payload.json
  payload-examples/api.github.com/deployment_status.with-installation.payload.json
  payload-examples/api.github.com/organization.member_added.with-installation.payload.json
  payload-examples/api.github.com/project.created.with-installation.payload.json
  payload-examples/api.github.com/project_column.created.with-installation.payload.json
  payload-examples/api.github.com/repository.created.with-installation.payload.json
Labels: maintenance

#248 feat: Use the common schemas for more properties of various schemas
  bin/validate-payload-examples.js
  payload-schemas/schemas/check_run.schema.json
  payload-schemas/schemas/check_suite.schema.json
  payload-schemas/schemas/common/repository.schema.json
  payload-schemas/schemas/common/user.schema.json
  payload-schemas/schemas/fork.schema.json
  payload-schemas/schemas/installation.schema.json
  payload-schemas/schemas/installation_repositories.schema.json
  payload-schemas/schemas/meta.schema.json
  payload-schemas/schemas/package.schema.json
  payload-schemas/schemas/pull_request.schema.json
  payload-schemas/schemas/pull_request_review.schema.json
  payload-schemas/schemas/pull_request_review_comment.schema.json
  payload-schemas/schemas/workflow_run.schema.json
Labels: feature

#256 feat: Update schemas with better types and use common schemas
  index.json
  payload-examples/api.github.com/security_advisory.updated.payload.json
  payload-schemas/schemas/check_run.schema.json
  payload-schemas/schemas/check_suite.schema.json
  payload-schemas/schemas/code_scanning_alert.schema.json
  payload-schemas/schemas/commit_comment.schema.json
  payload-schemas/schemas/common/repository.schema.json
  payload-schemas/schemas/deployment.schema.json
  payload-schemas/schemas/deployment_status.schema.json
  payload-schemas/schemas/installation.schema.json
  payload-schemas/schemas/issue_comment.schema.json
  payload-schemas/schemas/issues.schema.json
  payload-schemas/schemas/member.schema.json
  payload-schemas/schemas/membership.schema.json
  payload-schemas/schemas/milestone.schema.json
  payload-schemas/schemas/org_block.schema.json
  payload-schemas/schemas/organization.schema.json
  payload-schemas/schemas/package.schema.json
  payload-schemas/schemas/page_build.schema.json
  payload-schemas/schemas/project.schema.json
  payload-schemas/schemas/project_card.schema.json
  payload-schemas/schemas/pull_request.schema.json
  payload-schemas/schemas/pull_request_review.schema.json
  payload-schemas/schemas/pull_request_review_comment.schema.json
  payload-schemas/schemas/push.schema.json
  payload-schemas/schemas/release.schema.json
  payload-schemas/schemas/security_advisory.schema.json
  payload-schemas/schemas/sponsorship.schema.json
  payload-schemas/schemas/status.schema.json
  payload-schemas/schemas/workflow_run.schema.json
Labels: feature

#254 Convert scripts to typescript
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/update-prettier.yml
  .github/workflows/update.yml
  CONTRIBUTING.md
  README.md
  bin/octokit-schema.ts
  bin/octokit-webhooks.ts
  bin/validate-payload-examples.ts
  index.d.ts
  lib/cache.js
  lib/cache.ts
  lib/check-or-update-webhooks.js
  lib/check-or-update-webhooks.ts
  lib/get-actions-and-examples-from-payloads.js
  lib/get-actions-and-examples-from-payloads.ts
  lib/get-html.js
  lib/get-html.ts
  lib/get-sections.js
  lib/get-sections.ts
  lib/index.ts
  lib/section-to-webhook.js
  lib/section-to-webhook.ts
  lib/types.ts
  lib/workarounds.ts
  package-lock.json
  package.json
  payload-examples/README.md
  payload-schemas/index.ts
  schema.js
  test.js
  test.ts
  tsconfig.json
Labels: maintenance

#259 fix: Add the `content_url` property to `project_card` events
  index.json
  payload-examples/api.github.com/project_card/created.payload.json
  payload-examples/api.github.com/project_card/created.with-installation.payload.json
  payload-examples/api.github.com/project_card/created.with-organization.payload.json
  payload-examples/api.github.com/project_card/deleted.payload.json
  payload-examples/api.github.com/project_card/deleted.with-installation.payload.json
  payload-examples/api.github.com/project_card/deleted.with-organization.payload.json
  payload-schemas/schemas/project_card/converted.schema.json
  payload-schemas/schemas/project_card/created.schema.json
  payload-schemas/schemas/project_card/deleted.schema.json
  payload-schemas/schemas/project_card/edited.schema.json
  payload-schemas/schemas/project_card/moved.schema.json
Labels: bug

#261 chore: add script for formatting schemas & payloads with `prettier`
  bin/format-with-prettier.ts
Labels: maintenance

#262 build: make `bin/*` scripts executable
  bin/format-with-prettier.ts
  bin/octokit-schema.ts
  bin/octokit-webhooks.ts
  bin/validate-payload-examples.ts
Labels: maintenance

#263 ci(update): use `npm` script
  .github/workflows/update.yml
Labels: maintenance

#267 fix: use `additionalProperties` wherever we define an object
  payload-schemas/schemas/fork/event.schema.json
  payload-schemas/schemas/issue_comment/edited.schema.json
  payload-schemas/schemas/issues/edited.schema.json
  payload-schemas/schemas/member/edited.schema.json
  payload-schemas/schemas/milestone/edited.schema.json
  payload-schemas/schemas/project/edited.schema.json
  payload-schemas/schemas/public/event.schema.json
  payload-schemas/schemas/pull_request/edited.schema.json
  payload-schemas/schemas/pull_request_review_comment/edited.schema.json
  payload-schemas/schemas/release/edited.schema.json
  payload-schemas/schemas/repository/archived.schema.json
  payload-schemas/schemas/repository/edited.schema.json
  payload-schemas/schemas/repository/privatized.schema.json
  payload-schemas/schemas/repository/publicized.schema.json
  payload-schemas/schemas/repository/transferred.schema.json
  payload-schemas/schemas/repository/unarchived.schema.json
  payload-schemas/schemas/sponsorship/edited.schema.json
  payload-schemas/schemas/team/edited.schema.json
Labels: bug

#268 fix: title of `pull_request_review_comment$deleted` schema
  payload-schemas/schemas/pull_request_review_comment/deleted.schema.json
Labels: bug

#270 fix: various small fixes
  payload-schemas/schemas/check_run/completed.schema.json
  payload-schemas/schemas/common/repository.schema.json
  payload-schemas/schemas/fork/event.schema.json
  payload-schemas/schemas/public/event.schema.json
  payload-schemas/schemas/repository/archived.schema.json
  payload-schemas/schemas/repository/privatized.schema.json
  payload-schemas/schemas/repository/publicized.schema.json
  payload-schemas/schemas/repository/unarchived.schema.json
Labels: bug

#276 chore: improve validation script
  bin/validate-payload-examples.ts
Labels: maintenance

#275 fix: don't validate array as a tuple
  payload-schemas/schemas/issues/unpinned.schema.json
Labels: bug

#273 fix: unmerge union of types that are not null
  bin/optimize-schemas.ts
  payload-schemas/schemas/common/repository.schema.json
  payload-schemas/schemas/fork/event.schema.json
  payload-schemas/schemas/public/event.schema.json
  payload-schemas/schemas/repository/archived.schema.json
  payload-schemas/schemas/repository/privatized.schema.json
  payload-schemas/schemas/repository/publicized.schema.json
  payload-schemas/schemas/repository/unarchived.schema.json
Labels: bug

#278 fix: don't validate array as a tuple (again)
  payload-schemas/schemas/issues/assigned.schema.json
  payload-schemas/schemas/issues/closed.schema.json
  payload-schemas/schemas/issues/deleted.schema.json
  payload-schemas/schemas/issues/demilestoned.schema.json
  payload-schemas/schemas/issues/edited.schema.json
  payload-schemas/schemas/issues/labeled.schema.json
  payload-schemas/schemas/issues/locked.schema.json
  payload-schemas/schemas/issues/milestoned.schema.json
  payload-schemas/schemas/issues/opened.schema.json
  payload-schemas/schemas/issues/pinned.schema.json
  payload-schemas/schemas/issues/reopened.schema.json
  payload-schemas/schemas/issues/transferred.schema.json
  payload-schemas/schemas/issues/unassigned.schema.json
  payload-schemas/schemas/issues/unlabeled.schema.json
  payload-schemas/schemas/issues/unlocked.schema.json
Labels: bug

#274 refactor: merge `null` unions in schemas
  bin/optimize-schemas.ts
  payload-schemas/schemas/check_run/completed.schema.json
  payload-schemas/schemas/check_run/created.schema.json
  payload-schemas/schemas/check_run/requested_action.schema.json
  payload-schemas/schemas/check_run/rerequested.schema.json
  payload-schemas/schemas/check_suite/completed.schema.json
  payload-schemas/schemas/check_suite/requested.schema.json
  payload-schemas/schemas/check_suite/rerequested.schema.json
  payload-schemas/schemas/common/repository.schema.json
  payload-schemas/schemas/issue_comment/created.schema.json
  payload-schemas/schemas/issue_comment/deleted.schema.json
  payload-schemas/schemas/issue_comment/edited.schema.json
  payload-schemas/schemas/issues/assigned.schema.json
  payload-schemas/schemas/issues/closed.schema.json
  payload-schemas/schemas/issues/deleted.schema.json
  payload-schemas/schemas/issues/demilestoned.schema.json
  payload-schemas/schemas/issues/edited.schema.json
  payload-schemas/schemas/issues/labeled.schema.json
  payload-schemas/schemas/issues/locked.schema.json
  payload-schemas/schemas/issues/milestoned.schema.json
  payload-schemas/schemas/issues/opened.schema.json
  payload-schemas/schemas/issues/pinned.schema.json
  payload-schemas/schemas/issues/reopened.schema.json
  payload-schemas/schemas/issues/transferred.schema.json
  payload-schemas/schemas/issues/unassigned.schema.json
  payload-schemas/schemas/issues/unlabeled.schema.json
  payload-schemas/schemas/issues/unlocked.schema.json
  payload-schemas/schemas/issues/unpinned.schema.json
  payload-schemas/schemas/pull_request/assigned.schema.json
  payload-schemas/schemas/pull_request/closed.schema.json
  payload-schemas/schemas/pull_request/converted_to_draft.schema.json
  payload-schemas/schemas/pull_request/edited.schema.json
  payload-schemas/schemas/pull_request/labeled.schema.json
  payload-schemas/schemas/pull_request/locked.schema.json
  payload-schemas/schemas/pull_request/opened.schema.json
  payload-schemas/schemas/pull_request/ready_for_review.schema.json
  payload-schemas/schemas/pull_request/reopened.schema.json
  payload-schemas/schemas/pull_request/review_request_removed.schema.json
  payload-schemas/schemas/pull_request/review_requested.schema.json
  payload-schemas/schemas/pull_request/synchronize.schema.json
  payload-schemas/schemas/pull_request/unassigned.schema.json
  payload-schemas/schemas/pull_request/unlabeled.schema.json
  payload-schemas/schemas/pull_request/unlocked.schema.json
  payload-schemas/schemas/pull_request_review/submitted.schema.json
  payload-schemas/schemas/pull_request_review_comment/created.schema.json
  payload-schemas/schemas/pull_request_review_comment/deleted.schema.json
  payload-schemas/schemas/pull_request_review_comment/edited.schema.json
  payload-schemas/schemas/push/event.schema.json
  payload-schemas/schemas/security_advisory/performed.schema.json
  payload-schemas/schemas/security_advisory/published.schema.json
  payload-schemas/schemas/security_advisory/updated.schema.json
Labels: maintenance

#277 chore: enable strict-mode validation in ajv
  package.json
  payload-schemas/index.ts
Labels: maintenance

#279 fix: ensure all `object`s have `additionalProperties` in schemas
  bin/optimize-schemas.ts
  payload-schemas/schemas/check_run/created.schema.json
  payload-schemas/schemas/check_run/requested_action.schema.json
  payload-schemas/schemas/check_run/rerequested.schema.json
  payload-schemas/schemas/check_suite/completed.schema.json
  payload-schemas/schemas/check_suite/requested.schema.json
  payload-schemas/schemas/check_suite/rerequested.schema.json
  payload-schemas/schemas/issues/assigned.schema.json
  payload-schemas/schemas/issues/closed.schema.json
  payload-schemas/schemas/issues/deleted.schema.json
  payload-schemas/schemas/issues/demilestoned.schema.json
  payload-schemas/schemas/issues/edited.schema.json
  payload-schemas/schemas/issues/labeled.schema.json
  payload-schemas/schemas/issues/locked.schema.json
  payload-schemas/schemas/issues/milestoned.schema.json
  payload-schemas/schemas/issues/opened.schema.json
  payload-schemas/schemas/issues/pinned.schema.json
  payload-schemas/schemas/issues/reopened.schema.json
  payload-schemas/schemas/issues/transferred.schema.json
  payload-schemas/schemas/issues/unassigned.schema.json
  payload-schemas/schemas/issues/unlabeled.schema.json
  payload-schemas/schemas/issues/unlocked.schema.json
  payload-schemas/schemas/issues/unpinned.schema.json
  payload-schemas/schemas/label/edited.schema.json
  payload-schemas/schemas/organization/member_invited.schema.json
  payload-schemas/schemas/release/created.schema.json
  payload-schemas/schemas/release/deleted.schema.json
  payload-schemas/schemas/release/edited.schema.json
  payload-schemas/schemas/release/prereleased.schema.json
  payload-schemas/schemas/release/published.schema.json
  payload-schemas/schemas/release/released.schema.json
  payload-schemas/schemas/release/unpublished.schema.json
Labels: bug

#255 feat: generate types from schema
  .github/workflows/test.yml
  CONTRIBUTING.md
  README.md
  bin/octokit-types.ts
  package-lock.json
  package.json
  schema.d.ts
Labels: feature, typescript

#280 feat: create `repo-ref` common schema
  bin/ref-common-schemas.ts
  package.json
  payload-schemas/schemas/check_run/completed.schema.json
  payload-schemas/schemas/check_run/created.schema.json
  payload-schemas/schemas/check_run/requested_action.schema.json
  payload-schemas/schemas/check_run/rerequested.schema.json
  payload-schemas/schemas/check_suite/completed.schema.json
  payload-schemas/schemas/check_suite/requested.schema.json
  payload-schemas/schemas/check_suite/rerequested.schema.json
  payload-schemas/schemas/common/repo-ref.schema.json
  schema.d.ts
Labels: feature

#281 fix: add schemas for missing event actions
  payload-schemas/schemas/repository_dispatch/on-demand-test.schema.json
  payload-schemas/schemas/workflow_run/completed.schema.json
  payload-schemas/schemas/workflow_run/requested.schema.json
  schema.d.ts
Labels: bug

#283 refactor: create `asset` common schema
  bin/octokit-schema.ts
  package.json
  payload-schemas/schemas/common/asset.schema.json
  payload-schemas/schemas/release/created.schema.json
  payload-schemas/schemas/release/deleted.schema.json
  payload-schemas/schemas/release/edited.schema.json
  payload-schemas/schemas/release/prereleased.schema.json
  payload-schemas/schemas/release/published.schema.json
  payload-schemas/schemas/release/released.schema.json
  payload-schemas/schemas/release/unpublished.schema.json
  schema.d.ts
Labels: maintenance

#282 feat: export `WebhookEvent` type
  README.md
  bin/octokit-types.ts
  schema.d.ts
Labels: feature

#284 feat: generate `WebhookEventMap` & `WebhookEventName` type aliases
  bin/octokit-types.ts
  schema.d.ts
Labels: feature

#286 ci(update): update schema and types on changes from scraping the webhooks documentation
  .github/workflows/update.yml
Labels: maintenance

#287 fix: add types for items in arrays
  payload-schemas/schemas/check_run/completed.schema.json
  payload-schemas/schemas/check_run/created.schema.json
  payload-schemas/schemas/check_run/requested_action.schema.json
  payload-schemas/schemas/check_run/rerequested.schema.json
  payload-schemas/schemas/check_suite/completed.schema.json
  payload-schemas/schemas/check_suite/requested.schema.json
  payload-schemas/schemas/check_suite/rerequested.schema.json
  payload-schemas/schemas/installation/created.schema.json
  payload-schemas/schemas/installation/deleted.schema.json
  payload-schemas/schemas/installation/new_permissions_accepted.schema.json
  payload-schemas/schemas/installation/suspended.schema.json
  payload-schemas/schemas/installation/unsuspended.schema.json
  payload-schemas/schemas/installation_repositories/added.schema.json
  payload-schemas/schemas/installation_repositories/removed.schema.json
  payload-schemas/schemas/integration_installation/created.schema.json
  payload-schemas/schemas/integration_installation_repositories/added.schema.json
  schema.d.ts
Labels: bug

#290 Create common schema extractor
  bin/extract-common-schema.ts
  payload-schemas/schemas/common/sponsorship-tier.schema.json
  payload-schemas/schemas/sponsorship/cancelled.schema.json
  payload-schemas/schemas/sponsorship/created.schema.json
  payload-schemas/schemas/sponsorship/edited.schema.json
  payload-schemas/schemas/sponsorship/pending_cancellation.schema.json
  payload-schemas/schemas/sponsorship/pending_tier_change.schema.json
  payload-schemas/schemas/sponsorship/tier_changed.schema.json
  schema.d.ts
Labels: feature

#288 feat: add teams schema
  payload-schemas/schemas/common/team.schema.json
  payload-schemas/schemas/pull_request/assigned.schema.json
  payload-schemas/schemas/pull_request/closed.schema.json
  payload-schemas/schemas/pull_request/converted_to_draft.schema.json
  payload-schemas/schemas/pull_request/edited.schema.json
  payload-schemas/schemas/pull_request/labeled.schema.json
  payload-schemas/schemas/pull_request/locked.schema.json
  payload-schemas/schemas/pull_request/opened.schema.json
  payload-schemas/schemas/pull_request/ready_for_review.schema.json
  payload-schemas/schemas/pull_request/reopened.schema.json
  payload-schemas/schemas/pull_request/review_request_removed.schema.json
  payload-schemas/schemas/pull_request/review_requested.schema.json
  payload-schemas/schemas/pull_request/synchronize.schema.json
  payload-schemas/schemas/pull_request/unassigned.schema.json
  payload-schemas/schemas/pull_request/unlabeled.schema.json
  payload-schemas/schemas/pull_request/unlocked.schema.json
  payload-schemas/schemas/pull_request_review/submitted.schema.json
  payload-schemas/schemas/pull_request_review_comment/created.schema.json
  payload-schemas/schemas/pull_request_review_comment/deleted.schema.json
  payload-schemas/schemas/pull_request_review_comment/edited.schema.json
  schema.d.ts
Labels: feature

#291 feat: add common app schema
  payload-schemas/schemas/check_run/created.schema.json
  payload-schemas/schemas/check_run/requested_action.schema.json
  payload-schemas/schemas/check_run/rerequested.schema.json
  payload-schemas/schemas/check_suite/completed.schema.json
  payload-schemas/schemas/check_suite/requested.schema.json
  payload-schemas/schemas/check_suite/rerequested.schema.json
  payload-schemas/schemas/common/app.schema.json
  schema.d.ts
Labels: feature

#293 feat: use common app schema
  payload-schemas/schemas/check_run/completed.schema.json
  schema.d.ts
Labels: feature

#294 fix: adjust required properties
  payload-schemas/schemas/code_scanning_alert/appeared_in_branch.schema.json
  payload-schemas/schemas/code_scanning_alert/closed_by_user.schema.json
  payload-schemas/schemas/code_scanning_alert/created.schema.json
  payload-schemas/schemas/code_scanning_alert/fixed.schema.json
  payload-schemas/schemas/code_scanning_alert/reopened.schema.json
  payload-schemas/schemas/code_scanning_alert/reopened_by_user.schema.json
  payload-schemas/schemas/workflow_dispatch/event.schema.json
  payload-schemas/schemas/workflow_run/completed.schema.json
  payload-schemas/schemas/workflow_run/requested.schema.json
  schema.d.ts
Labels: feature

#295 chore: normalize references to common schemas when searching for refs
  bin/ref-common-schemas.ts
Labels: maintenance

#296 chore: remove `null` from type when extracting common schema
  bin/extract-common-schema.ts
Labels: maintenance

#297 feat: new example payload for push event
  index.json
  payload-examples/api.github.com/push/with-new-branch.payload.json
Labels: feature

#299 Adjust scripts
  bin/extract-common-schema.ts
  bin/ref-common-schemas.ts
Labels: maintenance

#292 feat: create `Committer` common schema
  payload-schemas/schemas/check_suite/completed.schema.json
  payload-schemas/schemas/check_suite/requested.schema.json
  payload-schemas/schemas/check_suite/rerequested.schema.json
  payload-schemas/schemas/common/committer.schema.json
  payload-schemas/schemas/push/event.schema.json
  payload-schemas/schemas/workflow_run/completed.schema.json
  payload-schemas/schemas/workflow_run/requested.schema.json
  schema.d.ts
Labels: feature

#300 fix: installation actions
  payload-schemas/schemas/installation/suspend.schema.json
  payload-schemas/schemas/installation/unsuspend.schema.json
  schema.d.ts
Labels: bug

#304 feat: add `pending_change` and `cancelled_pending_change`
  payload-schemas/schemas/marketplace_purchase/pending_change.schema.json
  payload-schemas/schemas/marketplace_purchase/pending_change_cancelled.schema.json
  schema.d.ts
Labels: feature

#302 feat: add `dismissed` and `edited` to `pull_request_review`
  index.json
  payload-examples/api.github.com/pull_request_review/dismissed.payload.json
  payload-schemas/schemas/pull_request_review/dismissed.schema..json
  payload-schemas/schemas/pull_request_review/edited.schema.json
  schema.d.ts
Labels: feature

#305 fix: add missing properties to pull_request_review.submitted
  index.json
  payload-examples/api.github.com/pull_request_review/submitted.payload.json
  payload-examples/api.github.com/pull_request_review/submitted.with-organization.payload.json
  payload-schemas/schemas/pull_request_review/submitted.schema.json
  schema.d.ts
Labels: bug

#306 fix: commit_comment can be made on a file itself
  index.json
  payload-examples/api.github.com/commit_comment/created.on-file.payload.json
  payload-schemas/schemas/commit_comment/created.schema.json
  schema.d.ts
Labels: bug

#308 fix: reference `user` common schema in a lot more places
  payload-schemas/schemas/deployment_status/created.schema.json
  payload-schemas/schemas/installation/created.schema.json
  payload-schemas/schemas/installation/deleted.schema.json
  payload-schemas/schemas/installation/new_permissions_accepted.schema.json
  payload-schemas/schemas/installation/suspend.schema.json
  payload-schemas/schemas/installation/unsuspend.schema.json
  payload-schemas/schemas/installation_repositories/added.schema.json
  payload-schemas/schemas/installation_repositories/removed.schema.json
  payload-schemas/schemas/integration_installation/created.schema.json
  payload-schemas/schemas/integration_installation_repositories/added.schema.json
  payload-schemas/schemas/pull_request/assigned.schema.json
  payload-schemas/schemas/pull_request/closed.schema.json
  payload-schemas/schemas/pull_request/converted_to_draft.schema.json
  payload-schemas/schemas/pull_request/edited.schema.json
  payload-schemas/schemas/pull_request/labeled.schema.json
  payload-schemas/schemas/pull_request/locked.schema.json
  payload-schemas/schemas/pull_request/opened.schema.json
  payload-schemas/schemas/pull_request/ready_for_review.schema.json
  payload-schemas/schemas/pull_request/reopened.schema.json
  payload-schemas/schemas/pull_request/review_request_removed.schema.json
  payload-schemas/schemas/pull_request/review_requested.schema.json
  payload-schemas/schemas/pull_request/synchronize.schema.json
  payload-schemas/schemas/pull_request/unassigned.schema.json
  payload-schemas/schemas/pull_request/unlabeled.schema.json
  payload-schemas/schemas/pull_request/unlocked.schema.json
  payload-schemas/schemas/pull_request_review/dismissed.schema..json
  payload-schemas/schemas/pull_request_review/edited.schema.json
  payload-schemas/schemas/pull_request_review/submitted.schema.json
  payload-schemas/schemas/status/event.schema.json
  schema.d.ts
Labels: bug

#307 feat: various little fixes and type improvements
  payload-schemas/schemas/check_run/completed.schema.json
  payload-schemas/schemas/check_run/created.schema.json
  payload-schemas/schemas/check_run/requested_action.schema.json
  payload-schemas/schemas/check_run/rerequested.schema.json
  payload-schemas/schemas/common/app.schema.json
  payload-schemas/schemas/common/organization.schema.json
  payload-schemas/schemas/common/repository.schema.json
  payload-schemas/schemas/pull_request_review_comment/created.schema.json
  schema.d.ts
Labels: feature

#309 chore: clone schemas before normalizing & improve `type` property check
  bin/ref-common-schemas.ts
Labels: maintenance

#310 fix: miscelaneous fixes to the schemas
  payload-schemas/schemas/common/team.schema.json
  payload-schemas/schemas/issue_comment/created.schema.json
  payload-schemas/schemas/issue_comment/deleted.schema.json
  payload-schemas/schemas/issue_comment/edited.schema.json
  payload-schemas/schemas/membership/added.schema.json
  payload-schemas/schemas/membership/removed.schema.json
  payload-schemas/schemas/repository/archived.schema.json
  payload-schemas/schemas/repository/privatized.schema.json
  payload-schemas/schemas/repository/publicized.schema.json
  payload-schemas/schemas/repository/unarchived.schema.json
  payload-schemas/schemas/star/created.schema.json
  payload-schemas/schemas/star/deleted.schema.json
  payload-schemas/schemas/status/event.schema.json
  payload-schemas/schemas/team/added_to_repository.schema.json
  payload-schemas/schemas/team/created.schema.json
  payload-schemas/schemas/team/deleted.schema.json
  payload-schemas/schemas/team/edited.schema.json
  payload-schemas/schemas/team/removed_from_repository.schema.json
  payload-schemas/schemas/team_add/event.schema.json
  schema.d.ts
Labels: bug

#311 feat: remove integration_installation & integration_installation_repositories
  payload-examples/api.github.com/integration_installation/created.payload.json
  payload-examples/api.github.com/integration_installation_repositories/added.payload.json
  payload-schemas/schemas/integration_installation/created.schema.json
  payload-schemas/schemas/integration_installation_repositories/added.schema.json
  schema.d.ts
Labels: feature

#316 feat: author_association common schema
  payload-schemas/schemas/commit_comment/created.schema.json
  payload-schemas/schemas/common/author_association.schema.json
  payload-schemas/schemas/issue_comment/created.schema.json
  payload-schemas/schemas/issue_comment/deleted.schema.json
  payload-schemas/schemas/issue_comment/edited.schema.json
  payload-schemas/schemas/issues/assigned.schema.json
  payload-schemas/schemas/issues/closed.schema.json
  payload-schemas/schemas/issues/deleted.schema.json
  payload-schemas/schemas/issues/demilestoned.schema.json
  payload-schemas/schemas/issues/edited.schema.json
  payload-schemas/schemas/issues/labeled.schema.json
  payload-schemas/schemas/issues/locked.schema.json
  payload-schemas/schemas/issues/milestoned.schema.json
  payload-schemas/schemas/issues/opened.schema.json
  payload-schemas/schemas/issues/pinned.schema.json
  payload-schemas/schemas/issues/reopened.schema.json
  payload-schemas/schemas/issues/transferred.schema.json
  payload-schemas/schemas/issues/unassigned.schema.json
  payload-schemas/schemas/issues/unlabeled.schema.json
  payload-schemas/schemas/issues/unlocked.schema.json
  payload-schemas/schemas/issues/unpinned.schema.json
  payload-schemas/schemas/pull_request/assigned.schema.json
  payload-schemas/schemas/pull_request/closed.schema.json
  payload-schemas/schemas/pull_request/converted_to_draft.schema.json
  payload-schemas/schemas/pull_request/edited.schema.json
  payload-schemas/schemas/pull_request/labeled.schema.json
  payload-schemas/schemas/pull_request/locked.schema.json
  payload-schemas/schemas/pull_request/opened.schema.json
  payload-schemas/schemas/pull_request/ready_for_review.schema.json
  payload-schemas/schemas/pull_request/reopened.schema.json
  payload-schemas/schemas/pull_request/review_request_removed.schema.json
  payload-schemas/schemas/pull_request/review_requested.schema.json
  payload-schemas/schemas/pull_request/synchronize.schema.json
  payload-schemas/schemas/pull_request/unassigned.schema.json
  payload-schemas/schemas/pull_request/unlabeled.schema.json
  payload-schemas/schemas/pull_request/unlocked.schema.json
  payload-schemas/schemas/pull_request_review/dismissed.schema..json
  payload-schemas/schemas/pull_request_review/edited.schema.json
  payload-schemas/schemas/pull_request_review/submitted.schema.json
  payload-schemas/schemas/pull_request_review_comment/created.schema.json
  payload-schemas/schemas/pull_request_review_comment/deleted.schema.json
  payload-schemas/schemas/pull_request_review_comment/edited.schema.json
  schema.d.ts
Labels: feature

#319 feat: create `Milestone` common schema
  payload-schemas/schemas/common/milestone.schema.json
  payload-schemas/schemas/common/pull-request.schema.json
  payload-schemas/schemas/issues/assigned.schema.json
  payload-schemas/schemas/issues/closed.schema.json
  payload-schemas/schemas/issues/deleted.schema.json
  payload-schemas/schemas/issues/demilestoned.schema.json
  payload-schemas/schemas/issues/edited.schema.json
  payload-schemas/schemas/issues/labeled.schema.json
  payload-schemas/schemas/issues/locked.schema.json
  payload-schemas/schemas/issues/milestoned.schema.json
  payload-schemas/schemas/issues/opened.schema.json
  payload-schemas/schemas/issues/pinned.schema.json
  payload-schemas/schemas/issues/reopened.schema.json
  payload-schemas/schemas/issues/transferred.schema.json
  payload-schemas/schemas/issues/unassigned.schema.json
  payload-schemas/schemas/issues/unlabeled.schema.json
  payload-schemas/schemas/issues/unlocked.schema.json
  payload-schemas/schemas/issues/unpinned.schema.json
  payload-schemas/schemas/milestone/closed.schema.json
  payload-schemas/schemas/milestone/created.schema.json
  payload-schemas/schemas/milestone/deleted.schema.json
  payload-schemas/schemas/milestone/edited.schema.json
  payload-schemas/schemas/milestone/opened.schema.json
  payload-schemas/schemas/pull_request/closed.schema.json
  payload-schemas/schemas/pull_request/converted_to_draft.schema.json
  payload-schemas/schemas/pull_request/opened.schema.json
  payload-schemas/schemas/pull_request/ready_for_review.schema.json
  payload-schemas/schemas/pull_request/reopened.schema.json
  payload-schemas/schemas/pull_request_review_comment/created.schema.json
  payload-schemas/schemas/pull_request_review_comment/deleted.schema.json
  payload-schemas/schemas/pull_request_review_comment/edited.schema.json
  schema.d.ts
Labels: feature

#324 fix: name of `installation` `suspend` & `unsuspend` action schemas
  payload-schemas/schemas/installation/suspend.schema.json
  payload-schemas/schemas/installation/unsuspend.schema.json
  schema.d.ts
Labels: bug

#326 fix: add missing permissions to `app` schema
  index.json
  payload-examples/api.github.com/check_suite/completed.1.payload.json
  payload-schemas/schemas/common/app.schema.json
  schema.d.ts
Labels: bug

#327 fix: add optional `organization` property to common repo schema
  index.json
  payload-examples/api.github.com/push/1.payload.json
  payload-schemas/schemas/common/repository.schema.json
  schema.d.ts
Labels: bug

#328 fix: update `issue_comment#created` schema
  index.json
  payload-examples/api.github.com/issue_comment/created.1.payload.json
  payload-schemas/schemas/issue_comment/created.schema.json
  schema.d.ts
Labels: bug

#322 fix: add missing property to pull_request.{review_requested, review_request_removed}
  index.json
  payload-examples/api.github.com/pull_request/review_request_removed.payload.json
  payload-examples/api.github.com/pull_request/review_requested.payload.json
  payload-schemas/schemas/pull_request/review_request_removed.schema.json
  payload-schemas/schemas/pull_request/review_requested.schema.json
  schema.d.ts
Labels: bug

#329 chore: create `diff-interface-schema` script
  bin/diff-interface-schemas.ts
Labels: maintenance

#330 chore: improve printing of validate errors when validating payloads
  bin/validate-payload-examples.ts
Labels: maintenance

#331 fix: improve usage of `milestone` common schema
  bin/octokit-types.ts
  payload-schemas/index.ts
  payload-schemas/schemas/common/simple-pull-request.schema.json
  payload-schemas/schemas/issue_comment/deleted.schema.json
  payload-schemas/schemas/issue_comment/edited.schema.json
  payload-schemas/schemas/milestone/closed.schema.json
  payload-schemas/schemas/milestone/created.schema.json
  payload-schemas/schemas/milestone/opened.schema.json
  schema.d.ts
Labels: bug

#332 feat: create `Link` interface
  bin/ref-common-schemas.ts
  payload-schemas/schemas/common/link.schema.json
  payload-schemas/schemas/common/pull-request.schema.json
  payload-schemas/schemas/common/simple-pull-request.schema.json
  payload-schemas/schemas/pull_request/closed.schema.json
  payload-schemas/schemas/pull_request/converted_to_draft.schema.json
  payload-schemas/schemas/pull_request/opened.schema.json
  payload-schemas/schemas/pull_request/ready_for_review.schema.json
  payload-schemas/schemas/pull_request/reopened.schema.json
  payload-schemas/schemas/pull_request_review/dismissed.schema.json
  payload-schemas/schemas/pull_request_review/edited.schema.json
  payload-schemas/schemas/pull_request_review/submitted.schema.json
  payload-schemas/schemas/pull_request_review_comment/created.schema.json
  payload-schemas/schemas/pull_request_review_comment/deleted.schema.json
  payload-schemas/schemas/pull_request_review_comment/edited.schema.json
  schema.d.ts
Labels: feature

#333 chore: format json files with prettier
  bin/format-with-prettier.ts
  payload-examples/api.github.com/check_run/requested_action.payload.json
  payload-examples/api.github.com/pull_request_review_comment/edited.payload.json
  payload-schemas/schemas/common/app.schema.json
  payload-schemas/schemas/common/label.schema.json
  payload-schemas/schemas/common/release-asset.schema.json
Labels: maintenance

#336 fix: optimize schemas
  bin/optimize-schemas.ts
  payload-schemas/schemas/check_run/completed.schema.json
  payload-schemas/schemas/check_run/rerequested.schema.json
  payload-schemas/schemas/code_scanning_alert/reopened_by_user.schema.json
  payload-schemas/schemas/installation_repositories/added.schema.json
Labels: bug

#335 feat: create `License` interface
  payload-schemas/schemas/common/license.schema.json
  payload-schemas/schemas/common/repository.schema.json
  payload-schemas/schemas/fork/event.schema.json
  payload-schemas/schemas/public/event.schema.json
  payload-schemas/schemas/repository/archived.schema.json
  payload-schemas/schemas/repository/privatized.schema.json
  payload-schemas/schemas/repository/publicized.schema.json
  payload-schemas/schemas/repository/unarchived.schema.json
  schema.d.ts
Labels: feature

#339 fix: remove `format` from `repository#homepage` property
  index.json
  payload-examples/api.github.com/label/created.1.payload.json
  payload-schemas/schemas/common/repository.schema.json
Labels: bug

#338 fix: mark `milestone` property as possibly `null` on `issue_comment`
  payload-schemas/schemas/issue_comment/deleted.schema.json
  payload-schemas/schemas/issue_comment/edited.schema.json
  schema.d.ts
Labels: bug

#337 fix: reference `Committer` interface in more places
  payload-schemas/schemas/common/commit.schema.json
  payload-schemas/schemas/common/committer.schema.json
  payload-schemas/schemas/status/event.schema.json
  schema.d.ts
Labels: bug

#340 fix: remove stray properties from `pull_request` schema
  payload-schemas/schemas/pull_request/review_request_removed.schema.json
  payload-schemas/schemas/pull_request/review_requested.schema.json
  schema.d.ts
Labels: bug

#341 fix: update schema for `milestone` property on `simple-pull-request`
  payload-schemas/schemas/common/simple-pull-request.schema.json
  schema.d.ts
Labels: bug

#342 refactor: move common functions in bin scripts into utils folder
  bin/diff-interface-schemas.ts
  bin/extract-common-schema.ts
  bin/format-with-prettier.ts
  bin/octokit-schema.ts
  bin/octokit-types.ts
  bin/optimize-schemas.ts
  bin/ref-common-schemas.ts
  bin/utils/argv.ts
  bin/utils/forEachJsonFile.ts
  bin/utils/getSchemaFromPath.ts
  bin/utils/index.ts
  bin/utils/loadMapOfSchemas.ts
  bin/utils/misc.ts
  bin/utils/normalizeSchema.ts
  bin/validate-payload-examples.ts
Labels: maintenance

#343 chore: refactor argv parsing for bin scripts to support `--help` flag
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  bin/diff-interface-schemas.ts
  bin/docs/diff-interface-schemas.md
  bin/docs/extract-common-schema.md
  bin/docs/format-with-prettier.md
  bin/docs/octokit-schema.md
  bin/docs/octokit-types.md
  bin/docs/optimize-schemas.md
  bin/docs/ref-common-schemas.md
  bin/docs/validate-payload-examples.md
  bin/extract-common-schema.ts
  bin/format-with-prettier.ts
  bin/octokit-schema.ts
  bin/octokit-types.ts
  bin/optimize-schemas.ts
  bin/ref-common-schemas.ts
  bin/utils/argv.ts
  bin/utils/misc.ts
  bin/validate-payload-examples.ts
  payload-examples/README.md
Labels: maintenance
