Repository octokit/webhooks, pull requests merged in 2022-08, with the labels that each got.

#686 fix: correct `MergeGroupChecksRequestedEvent` schema title
  payload-schemas/api.github.com/merge_group/checks_requested.schema.json
  payload-types/schema.d.ts
Labels: bug

#690 fix: `changes` property can be undefined in `branch_protection_rule#edited`, add missing keys to `changes` property in `branch_protection_rule#edited`, new `blocking` permission for apps
  payload-examples/api.github.com/branch_protection_rule/edited.payload.json
  payload-examples/api.github.com/index.json
  payload-schemas/api.github.com/branch_protection_rule/edited.schema.json
  payload-schemas/api.github.com/common/app.schema.json
  payload-schemas/api.github.com/common/installation.schema.json
  payload-types/schema.d.ts
Labels: bug

#695 fix: update schema descriptions for `added`, `removed` and `modified` files in `commits`
  payload-schemas/api.github.com/common/commit.schema.json
  payload-types/schema.d.ts
Labels: documentation, maintenance

#694 ci(update): add notes to PR body about modifying schemas
  .github/workflows/update.yml
Labels: maintenance

#693 fix: correct `enum` values for `required_conversation_resolution_level`, add enum values for `PullRequestReview#state`
  payload-schemas/api.github.com/branch_protection_rule/edited.schema.json
  payload-schemas/api.github.com/pull_request_review/edited.schema.json
  payload-schemas/api.github.com/pull_request_review/submitted.schema.json
  payload-types/schema.d.ts
Labels: bug

#696 fix: refactor `BranchProtectionRule` to have a common schema for the different rule types
  payload-schemas/api.github.com/branch_protection_rule/edited.schema.json
  payload-schemas/api.github.com/common/branch-protection-rule-array.schema.json
  payload-schemas/api.github.com/common/branch-protection-rule-boolean.schema.json
  payload-schemas/api.github.com/common/branch-protection-rule-enforcement-level.schema.json
  payload-schemas/api.github.com/common/branch-protection-rule-number.schema.json
  payload-schemas/api.github.com/common/branch-protection-rule.schema.json
  payload-types/schema.d.ts
Labels: maintenance
